<a href="https://colab.research.google.com/github/Sheharyar3364/Deep-Learning-With-PyTorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
my_list = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [5]:
## NUMPY ARRAYS
np1 = np.random.rand(3,4)
np1

array([[0.10742398, 0.55284625, 0.90309189, 0.98816504],
       [0.80140009, 0.54047016, 0.38489855, 0.30648491],
       [0.24066049, 0.10006682, 0.61670198, 0.48831159]])

In [7]:
## Tensors
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-1.0009, -2.1817, -0.2688, -1.0124],
        [-0.1516, -1.4484, -0.6762, -0.4227],
        [-0.2632, -0.1332,  0.6372,  1.0764]])

In [11]:
np1.dtype

dtype('float64')

In [8]:
tensor_2d.dtype

torch.float32

In [9]:
## 3D Tensors
tensor_3d = torch.zeros(2, 3, 4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
tensor_3d.dtype

torch.float32

In [12]:
## Create tensor out of numpy array

In [13]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.1074, 0.5528, 0.9031, 0.9882],
        [0.8014, 0.5405, 0.3849, 0.3065],
        [0.2407, 0.1001, 0.6167, 0.4883]], dtype=torch.float64)