<a href="https://colab.research.google.com/github/Sheharyar3364/Deep-Learning-With-PyTorch/blob/main/Tensors_operators.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
## Reshape & View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
# Reshape if we don't know the number of items using negative 1
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
my_torch2 = my_torch2.reshape(2, -1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
## We can go in negative direction now, by using negative 1 in the first argument instead of 2nd
my_torch3 = torch.arange(15)
my_torch3

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
my_torch3 = my_torch3.reshape(-1, 3)
my_torch3

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [15]:
## same thing can be done with view
my_torch4 = torch.arange(10)
my_torch4

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
my_torch5 = my_torch.view(2, 5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
 ## With reshape and View, they will update
my_torch6 = torch.arange(10)
my_torch6

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
my_torch7 = my_torch6.reshape(2, 5)
my_torch7

tensor([[   0,    1,    2,    3,    4],
        [4141, 4141, 4141, 4141, 4141]])

In [30]:
my_torch6[1] = 5151
my_torch6

tensor([[   0,    1,    2,    3,    4],
        [5151, 5151, 5151, 5151, 5151]])

In [31]:
my_torch8 = torch.arange(10)
my_torch8

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
## Slices
## Grab a specific item
my_torch8[7]

tensor(7)

In [33]:
my_torch9 = my_torch.reshape(5,2)
my_torch9

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [34]:
## Second column
my_torch9[:,1]

tensor([1, 3, 5, 7, 9])

In [35]:
## return second column but with brackets
my_torch9[:, 1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])